namespace: example-override

services:
  example1:
    name: example1-override
  example2:
    name: example2-overrride
    ports:
      - name: http
        port: 8081
        protocol: TCP
        targetPort: 8081
