namespace:
  name: example
  labels:
    sharedGateway: "true"

serviceAccount:
  name: example

gateway:
  name: example-gateway
  namespace: infra
  address: public-ip
  hosts:
    - name: example-com-https
      hostname: example.com
      tls: cloudflare-origin-ssl
    - name: sub-example-com-https
      hostname: sub.example.com
      tls: cloudflare-origin-ssl

httpRoutes:
  - name: example-route
    gateway:
      name: example-gateway
      namespace: infra
    hostnames:
      - example.com
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /hr
        backendRefs:
          - kind: Service
            name: echo-hr
            port: 9080

services:
  example1:
    name: example1
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
  example2:
    name: example2
    type: NodePort
    ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080

deployments:
  deploy1:
    name: Deployment 1
    replicas: 1
    containers:
      app:
        name: container1
        image:
          repository: example1-repository.com
          tag: latest
        env:
          - name: EXAMPLE1_ENV
            value: example1
        ports:
          - name: http
            containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9090
            scheme: HTTP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
  deploy2:
    name: Deployment 2
    replicas: 1
    containers:
      app:
        name: container2
        image:
          repository: example2-repository.com
          tag: latest
        env:
          - name: EXAMPLE2_ENV
            value: example2
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
