namespace: example

serviceAccount:
  name: example

ingresses:
  example-ingress:
    ip: 1.1.1.1
    tls: "secret-name"
    name: example-ingress
    rules:
      - host: example.com
        http:
          paths:
          - path: /bar
            pathType: Prefix
            backend:
              service:
                name: service2
                port:
                  number: 8080

services:
  example1:
    name: example1
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
  example2:
    name: example2
    ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080

deployments:
  deploy1:
    name: Deployment 1
    replicas: 1
    containers:
      app:
        name: container1
        image:
          repository: example1-repository.com
          tag: latest
        env:
          - name: EXAMPLE1_ENV
            value: example1
        ports:
          - name: http
            containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
  deploy2:
    name: Deployment 2
    replicas: 1
    containers:
      app:
        name: container2
        image:
          repository: example2-repository.com
          tag: latest
        env:
          - name: EXAMPLE2_ENV
            value: example2
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
