{{- define "helm-library.gateway.tpl" -}}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  addresses:
    - type: NamedAddress
      value: {{ .Values.gateway.address }}
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      hostname: {{ .Values.gateway.hostname }}
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              sharedGateway: "true"
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.gateway.tls }}
            kind: Secret
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.gateway.name }}-http-redirect
  namespace: {{ .Values.gateway.namespace }}
spec:
  parentRefs:
    - namespace: {{ .Values.gateway.namespace }}
      name: {{ .Values.gateway.name }}
      sectionName: http
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
{{- end -}}
