{{- define "helm-library.gateway.tpl" -}}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: gke-l7-gxlb
  listeners:
    - name: shared-http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              {{ print "shared-gateway-" (.Values.gateway.name | toString) }}: "true"
{{- end -}}
