{{- define "helm-library.gateway.tpl" -}}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  addresses:
    - type: NamedAddress
      value: {{ .Values.gateway.address }}
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    {{- range $host := .Values.gateway.hosts }}
    - name: {{ $host.name }}
      hostname: {{ $host.hostname }}
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              sharedGateway: "true"
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ $host.tls }}
            kind: Secret
    {{- end }}
{{- end -}}
