{{- define "helm-library.httpRoutes.tpl" -}}
{{- $namespace := .Values.namespace.name -}}
{{ range $httpRoute := .Values.httpRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ $httpRoute.name }}
  namespace: {{ $namespace }}
  labels:
    shared-gateway-access: {{ $httpRoute.gateway.name }}
spec:
  parentRefs:
    - name: {{ $httpRoute.gateway.name }}
      namespace: {{ $httpRoute.gateway.namespace }}
  hostnames:
    {{ toYaml $httpRoute.hostnames | nindent 4 }}
  rules:
    {{ toYaml $httpRoute.rules | nindent 4 }}
{{- end -}}
{{- end -}}
