{{- define "helm-library.ingresses.tpl" -}}
{{ range $ingress := .Values.ingresses }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingress.name }}
spec:
  rules:
    {{ toYaml $ingress.rules | nindent 4 }}
{{- end -}}
{{- end -}}