{{- define "helm-library.namespace.tpl" -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    "app.kubernetes.io/managed-by": "Helm"
  {{- if .Values.namespace.labels }}
    {{ toYaml .Values.namespace.labels | nindent 4 }}
  {{- end }}
{{- end -}}
