{{- define "helm-library.secret.tpl" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  {{- range $name, $value := .Values.secret_values }}
  {{ $name }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end -}}
