{{- define "helm-library.serviceAccount.tpl" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
{{- end -}}
