{{- define "helm-library.services.tpl" -}}
{{- $namespace := .Values.namespace -}}
{{ range $key, $value := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}
  namespace: {{ $namespace }}
spec:
  type: ClusterIP
  ports:
    {{ toYaml $value.ports | nindent 4 }}
  selector:
    app: {{ $value.name }}
{{- end -}}
{{- end -}}