{{- define "helm-library.service.tpl" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ . }}
spec:
  type: ClusterIP
  ports:
  {{ toYaml .Values.service.ports | nindent 2 }}
  selector:
    app: {{ .Values.service.selector }}
{{- end -}}
