{{- define "helm-library.services.tpl" -}}
{{- $namespace := .Values.namespace.name -}}
{{ range $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ $namespace }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  ports:
    {{ toYaml $service.ports | nindent 4 }}
  selector:
    app: {{ $service.name }}
{{- end -}}
{{- end -}}
