name: Package and push

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: alex-cloud-438416
  WORKLOAD_IDENTITY_PROVIDER: projects/38127965315/locations/global/workloadIdentityPools/github-actions/providers/github
  SERVICE_ACCOUNT: github-agent@alex-cloud-438416.iam.gserviceaccount.com
  CLUSTER: alex-cloud-1
  REGION: us-central1
  ZONE: us-central1-c

jobs:
  package_and_push:
    name: Package and Push
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Set up K8S config
        run: |-
          gcloud container clusters get-credentials ${{ env.CLUSTER }} --zone ${{ env.ZONE }}

      - name: Build
        run: helm dependency build example/

      - name: Test
        run: helm install example example/ -f example/values.yaml -f example/values.override.yaml --dry-run --debug

      - name: Helm login
        run: export HELM_EXPERIMENTAL_OCI=1 && gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://${{ env.REGION }}-docker.pkg.dev

      - name: Package helm library
        run: helm package helm-library

      - name: Get current version
        run: echo "CURRENT_VERSION=$(grep 'version:' helm-library/Chart.yaml | sed 's/.*\ //g')" >> $GITHUB_ENV

      - name: Push helm library
        run: export HELM_EXPERIMENTAL_OCI=1 && helm push helm-library-${{ env.CURRENT_VERSION }}.tgz oci://${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/helm-library

      - name: Show pushed version
        run: echo ${{ env.CURRENT_VERSION }}
